[env:nucleo_f401re]
platform = ststm32
board = nucleo_f401re
framework = cmsis

; macOS 64-bit güncel derleyici paketini zorunlu kıl
platform_packages =
    toolchain-gccarmnoneeabi@~1.100301.0

monitor_speed = 115200